### ISSUE TITLE
output is mask, not t1

### ISSUE THREAD

**Issue by svincibo** [anibalsolon/HD-BET_app#1]
The app currently produces a mask, but is outputted as an anat/t1w datatype instead of the mask datatype. This will cause issues with using the output of the app -- which is a shame, because it does a wonderful job extracting the brain!

**Comment by soichih** [comment]
@anibalsolon I've made a PR to switch the output (https://github.com/anibalsolon/HD-BET_app/pull/2) Could you review it?

**Comment by anibalsolon** [comment]
Thank you for reporting @svincibo , @soichih 's PR is merged now
